# When specifying that a job has a container, that job is run IN the container.
# It does not have access to docker.

name: Container with service

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/container-with-service.yml'

jobs:
  container-with-service:
    runs-on: ubuntu-latest
    container: node:18-bullseye
    services:
      mongodb:
        image: mongo:latest
        
    steps:
      - name: Print info
        run: |
          node -v
          pwd
