name: Service containers

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/service-containers.yml'

jobs:
  service-containers:
    runs-on: ubuntu-latest
    container: node:18-bullseye
    services:
      mongodb:
        image: mongo:latest
        
    steps:
      - name: Print info
        run: |
          lsb-release-a
          ls /
          pwd
          # This doesn't work; we are running inside a container, it doesn't have docker.
          #docker ps
      
    
